version: "3.7"

services:
  web:
    build:
      target: django-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./exampleproject:/exampleproject
    ports:
      - "8000:8000"
    depends_on:
      - vue

  vue:
    build:
      context: .
      target: vue-dev
    command: npm run dev
    volumes:
      - ./exampleproject/frontend:/usr/src/app
      # Prevent the host's node_modules overwriting the container's at run time
      - node_modules:/usr/src/app/node_modules
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  node_modules: